In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('precipitation.csv', parse_dates=[2])

In [7]:
data

,station,name,date,latitude,longitude,elevation,precipitation
0,CA001101158,BURNABY SIMON FRASER U,2016-01-01,49.2833,-122.9167,366.0,0
1,CA001101158,BURNABY SIMON FRASER U,2016-01-02,49.2833,-122.9167,366.0,0
2,CA001101158,BURNABY SIMON FRASER U,2016-01-03,49.2833,-122.9167,366.0,10
3,CA001101158,BURNABY SIMON FRASER U,2016-01-04,49.2833,-122.9167,366.0,15
4,CA001101158,BURNABY SIMON FRASER U,2016-01-05,49.2833,-122.9167,366.0,80
5,CA001101158,BURNABY SIMON FRASER U,2016-01-07,49.2833,-122.9167,366.0,10
6,CA001101158,BURNABY SIMON FRASER U,2016-01-08,49.2833,-122.9167,366.0,6
7,CA001101158,BURNABY SIMON FRASER U,2016-01-09,49.2833,-122.9167,366.0,0
8,CA001101158,BURNABY SIMON FRASER U,2016-01-10,49.2833,-122.9167,366.0,0
9,CA001101158,BURNABY SIMON FRASER U,2016-01-11,49.2833,-122.9167,366.0,85
10,CA001101158,BURNABY SIMON FRASER U,2016-01-12,49.2833,-122.9167,366.0,56
11,CA001101158,BURNABY SIMON FRASER U,2016-01-13,49.2833,-122.9167,366.0,8
12,CA001101158,BURNABY SIMON FRASER U,2016-01-14,49.2833,-122.9167,366.0,4
13,CA001101158,BURNABY SIMON FRASER U,2016-01-15,49.2833,-122.9167,366.0,4
14,CA001101158,BURNABY SIMON FRASER U,2016-01-16,49.2833,-122.9167,366.0,104
15,CA001101158,BURNABY SIMON FRASER U,2016-01-17,49.2833,-122.9167,366.0,96
16,CA001101158,BURNABY SIMON FRASER U,2016-01-18,49.2833,-122.9167,366.0,42
17,CA001101158,BURNABY SIMON FRASER U,2016-01-19,49.2833,-122.9167,366.0,5
18,CA001101158,BURNABY SIMON FRASER U,2016-01-20,49.2833,-122.9167,366.0,0
19,CA001101158,BURNABY SIMON FRASER U,2016-01-21,49.2833,-122.9167,366.0,223
20,CA001101158,BURNABY SIMON FRASER U,2016-01-22,49.2833,-122.9167,366.0,18
21,CA001101158,BURNABY SIMON FRASER U,2016-01-23,49.2833,-122.9167,366.0,46
22,CA001101158,BURNABY SIMON FRASER U,2016-01-24,49.2833,-122.9167,366.0,22
23,CA001101158,BURNABY SIMON FRASER U,2016-01-25,49.2833,-122.9167,366.0,34
24,CA001101158,BURNABY SIMON FRASER U,2016-01-26,49.2833,-122.9167,366.0,318
25,CA001101158,BURNABY SIMON FRASER U,2016-01-27,49.2833,-122.9167,366.0,545
26,CA001101158,BURNABY SIMON FRASER U,2016-01-28,49.2833,-122.9167,366.0,6
27,CA001101158,BURNABY SIMON FRASER U,2016-01-29,49.2833,-122.9167,366.0,10
28,CA001101158,BURNABY SIMON FRASER U,2016-01-30,49.2833,-122.9167,366.0,62
29,CA001101158,BURNABY SIMON FRASER U,2016-01-31,49.2833,-122.9167,366.0,0
...,...,...,...,...,...,...,...
3142,CA002204101,YELLOWKNIFE A,2016-12-01,62.4667,-114.4333,206.0,10
3143,CA002204101,YELLOWKNIFE A,2016-12-02,62.4667,-114.4333,206.0,12
3144,CA002204101,YELLOWKNIFE A,2016-12-03,62.4667,-114.4333,206.0,12
3145,CA002204101,YELLOWKNIFE A,2016-12-04,62.4667,-114.4333,206.0,16
3146,CA002204101,YELLOWKNIFE A,2016-12-05,62.4667,-114.4333,206.0,8
3147,CA002204101,YELLOWKNIFE A,2016-12-06,62.4667,-114.4333,206.0,0
3148,CA002204101,YELLOWKNIFE A,2016-12-07,62.4667,-114.4333,206.0,0
3149,CA002204101,YELLOWKNIFE A,2016-12-08,62.4667,-114.4333,206.0,4
3150,CA002204101,YELLOWKNIFE A,2016-12-09,62.4667,-114.4333,206.0,0
3151,CA002204101,YELLOWKNIFE A,2016-12-11,62.4667,-114.4333,206.0,0
3152,CA002204101,YELLOWKNIFE A,2016-12-12,62.4667,-114.4333,206.0,8
3153,CA002204101,YELLOWKNIFE A,2016-12-13,62.4667,-114.4333,206.0,0
3154,CA002204101,YELLOWKNIFE A,2016-12-14,62.4667,-114.4333,206.0,4
3155,CA002204101,YELLOWKNIFE A,2016-12-15,62.4667,-114.4333,206.0,0
3156,CA002204101,YELLOWKNIFE A,2016-12-16,62.4667,-114.4333,206.0,0
3157,CA002204101,YELLOWKNIFE A,2016-12-17,62.4667,-114.4333,206.0,0
3158,CA002204101,YELLOWKNIFE A,2016-12-18,62.4667,-114.4333,206.0,0
3159,CA002204101,YELLOWKNIFE A,2016-12-19,62.4667,-114.4333,206.0,0
3160,CA002204101,YELLOWKNIFE A,2016-12-20,62.4667,-114.4333,206.0,20
3161,CA002204101,YELLOWKNIFE A,2016-12-21,62.4667,-114.4333,206.0,4
3162,CA002204101,YELLOWKNIFE A,2016-12-22,62.4667,-114.4333,206.0,0
3163,CA002204101,YELLOWKNIFE A,2016-12-23,62.4667,-114.4333,206.0,0
3164,CA002204101,YELLOWKNIFE A,2016-12-24,62.4667,-114.4333,206.0,2
3165,CA002204101,YELLOWKNIFE A,2016-12-25,62.4667,-114.4333,206.0,2
3166,CA002204101,YELLOWKNIFE A,2016-12-26,62.4667,-114.4333,206.0,0
3167,CA002204101,YELLOWKNIFE A,2016-12-27,62.4667,-114.4333,206.0,0
3168,CA002204101,YELLOWKNIFE A,2016-12-28,62.4667,-114.4333,206.0,0
3169,CA002204101,YELLOWKNIFE A,2016-12-29,62.4667,-114.4333,206.0,0
3170,CA002204101,YELLOWKNIFE A,2016-12-30,62.4667,-114.4333,206.0,12
3171,CA002204101,YELLOWKNIFE A,2016-12-31,62.4667,-114.4333,206.0,2

In [3]:
def date_to_month(d):
    # You may need to modify this function, depending on your data types.
    return '%04i-%02i' % (d.year, d.month)

In [8]:
data['month'] = data['date'].apply(date_to_month)

In [13]:
grouped_data = data.groupby(['name', 'month'])

In [27]:
monthly_new_data = grouped_data.aggregate('sum').reset_index()

In [28]:
monthly_new_data

,name,month,latitude,longitude,elevation,precipitation
0,BURNABY SIMON FRASER U,2016-01,1478.4990,-3687.5010,10980.0,1809
1,BURNABY SIMON FRASER U,2016-02,1084.2326,-2704.1674,8052.0,1482
2,BURNABY SIMON FRASER U,2016-03,1478.4990,-3687.5010,10980.0,2159
3,BURNABY SIMON FRASER U,2016-04,1478.4990,-3687.5010,10980.0,374
4,BURNABY SIMON FRASER U,2016-05,1034.9493,-2581.2507,7686.0,606
5,BURNABY SIMON FRASER U,2016-06,1034.9493,-2581.2507,7686.0,428
6,BURNABY SIMON FRASER U,2016-07,985.6660,-2458.3340,7320.0,442
7,BURNABY SIMON FRASER U,2016-08,1232.0825,-3072.9175,9150.0,68
8,BURNABY SIMON FRASER U,2016-09,985.6660,-2458.3340,7320.0,956
9,BURNABY SIMON FRASER U,2016-10,936.3827,-2335.4173,6954.0,1429
10,BURNABY SIMON FRASER U,2016-11,837.8161,-2089.5839,6222.0,1349
11,BURNABY SIMON FRASER U,2016-12,788.5328,-1966.6672,5856.0,1846
12,CALGARY INTL A,2016-01,1584.6177,-3534.5177,33604.0,121
13,CALGARY INTL A,2016-02,1482.3843,-3306.4843,31436.0,22
14,CALGARY INTL A,2016-03,1584.6177,-3534.5177,33604.0,46
15,CALGARY INTL A,2016-04,1533.5010,-3420.5010,32520.0,40
16,CALGARY INTL A,2016-05,1584.6177,-3534.5177,33604.0,683
17,CALGARY INTL A,2016-06,1533.5010,-3420.5010,32520.0,616
18,CALGARY INTL A,2016-07,1584.6177,-3534.5177,33604.0,2061
19,CALGARY INTL A,2016-08,1533.5010,-3420.5010,32520.0,834
20,CALGARY INTL A,2016-09,1533.5010,-3420.5010,32520.0,253
21,CALGARY INTL A,2016-10,1533.5010,-3420.5010,32520.0,276
22,CALGARY INTL A,2016-11,1533.5010,-3420.5010,32520.0,27
23,CALGARY INTL A,2016-12,1533.5010,-3420.5010,32520.0,224
24,GANDER INTL A,2016-01,1516.9323,-1691.5677,4681.0,896
25,GANDER INTL A,2016-02,1419.0657,-1582.4343,4379.0,1232
26,GANDER INTL A,2016-03,1516.9323,-1691.5677,4681.0,992
27,GANDER INTL A,2016-04,1467.9990,-1637.0010,4530.0,1106
28,GANDER INTL A,2016-05,1467.9990,-1637.0010,4530.0,1236
29,GANDER INTL A,2016-06,1467.9990,-1637.0010,4530.0,1015
...,...,...,...,...,...,...
78,TORONTO LESTER B. PEARSON INT',2016-07,1354.1823,-2468.6323,5363.0,399
79,TORONTO LESTER B. PEARSON INT',2016-08,1354.1823,-2468.6323,5363.0,667
80,TORONTO LESTER B. PEARSON INT',2016-09,1310.4990,-2388.9990,5190.0,663
81,TORONTO LESTER B. PEARSON INT',2016-10,1354.1823,-2468.6323,5363.0,452
82,TORONTO LESTER B. PEARSON INT',2016-11,1266.8157,-2309.3657,5017.0,497
83,TORONTO LESTER B. PEARSON INT',2016-12,1354.1823,-2468.6323,5363.0,821
84,VANCOUVER INTL A,2016-01,1476.0000,-3695.4990,120.0,1682
85,VANCOUVER INTL A,2016-02,1377.6000,-3449.1324,112.0,1304
86,VANCOUVER INTL A,2016-03,1525.2000,-3818.6823,124.0,1616
87,VANCOUVER INTL A,2016-04,1476.0000,-3695.4990,120.0,242
88,VANCOUVER INTL A,2016-05,1476.0000,-3695.4990,120.0,516
89,VANCOUVER INTL A,2016-06,1426.8000,-3572.3157,116.0,582
90,VANCOUVER INTL A,2016-07,1476.0000,-3695.4990,120.0,328
91,VANCOUVER INTL A,2016-08,1525.2000,-3818.6823,124.0,138
92,VANCOUVER INTL A,2016-09,1476.0000,-3695.4990,120.0,784
93,VANCOUVER INTL A,2016-10,1525.2000,-3818.6823,124.0,2034
94,VANCOUVER INTL A,2016-11,1476.0000,-3695.4990,120.0,2402
95,VANCOUVER INTL A,2016-12,1476.0000,-3695.4990,120.0,1520
96,YELLOWKNIFE A,2016-01,1936.4677,-3547.4323,6386.0,220
97,YELLOWKNIFE A,2016-02,1749.0676,-3204.1324,5768.0,90
98,YELLOWKNIFE A,2016-03,1936.4677,-3547.4323,6386.0,28
99,YELLOWKNIFE A,2016-04,1874.0010,-3432.9990,6180.0,120
100,YELLOWKNIFE A,2016-05,1936.4677,-3547.4323,6386.0,98
101,YELLOWKNIFE A,2016-06,1874.0010,-3432.9990,6180.0,306
102,YELLOWKNIFE A,2016-07,1936.4677,-3547.4323,6386.0,154
103,YELLOWKNIFE A,2016-08,1936.4677,-3547.4323,6386.0,280
104,YELLOWKNIFE A,2016-09,1874.0010,-3432.9990,6180.0,488
105,YELLOWKNIFE A,2016-10,1874.0010,-3432.9990,6180.0,158
106,YELLOWKNIFE A,2016-11,1874.0010,-3432.9990,6180.0,176
107,YELLOWKNIFE A,2016-12,1874.0010,-3432.9990,6180.0,116

In [29]:
monthly = monthly_new_data.pivot(index='name', columns='month', values='precipitation')

In [30]:
monthly

month,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12
name,,,,,,,,,,,,
BURNABY SIMON FRASER U,1809,1482,2159,374,606,428,442,68,956,1429,1349,1846
CALGARY INTL A,121,22,46,40,683,616,2061,834,253,276,27,224
GANDER INTL A,896,1232,992,1106,1236,1015,1264,1096,1026,2422,1184,1099
HALIFAX INTL A,1491,1473,1452,1595,1001,725,734,445,845,2185,1305,1835
REVELSTOKE,930,561,533,204,546,748,662,274,785,1620,1293,295
SHERBROOKE,183,982,621,471,667,671,525,1599,433,1176,594,627
TORONTO LESTER B. PEARSON INT',363,491,729,681,346,269,399,667,663,452,497,821
VANCOUVER INTL A,1682,1304,1616,242,516,582,328,138,784,2034,2402,1520
YELLOWKNIFE A,220,90,28,120,98,306,154,280,488,158,176,116

In [31]:
counts_new_data = grouped_data.aggregate('count').reset_index()

In [32]:
counts = counts_new_data.pivot(index='name', columns='month', values='precipitation')

In [33]:
counts

month,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12
name,,,,,,,,,,,,
BURNABY SIMON FRASER U,30,22,30,30,21,21,20,25,20,19,17,16
CALGARY INTL A,31,29,31,30,31,30,31,30,30,30,30,30
GANDER INTL A,31,29,31,30,30,30,31,31,30,31,30,31
HALIFAX INTL A,31,29,31,30,31,30,31,31,29,30,30,31
REVELSTOKE,31,29,31,29,31,29,30,31,30,31,30,29
SHERBROOKE,31,29,31,30,31,30,28,31,30,30,29,31
TORONTO LESTER B. PEARSON INT',31,28,31,30,31,30,31,31,30,31,29,31
VANCOUVER INTL A,30,28,31,30,30,29,30,31,30,31,30,30
YELLOWKNIFE A,31,28,31,30,31,30,31,31,30,30,30,30